### PR TITLE
highway fill mode made by axua

### PR DESCRIPTION
**Pull request by r-33**
needs to be edited to check what direction you're facing i think but idk how to do that...

### CODE REVIEW

**Comment by ionar2** [comment]
This reverts the code updates I did today. What does highway fill mode do? Just makes a wall in your facing direction?

**Comment by r-33** [comment]
it makes a highway sized wall yes. I was just giving you the source. to save you some time. Ppl supposedly want this sort of option...

**Comment by r-33** [comment]
im not really sure what im doing I dont really understand how to use github but yeah

**Comment by ionar2** [comment]
This won't be accepted but I will implement the option for highway wall in a better way.

**Pull request closed without merging**
