### PR TITLE
Add workflow file

### PR DESCRIPTION
**Pull request by AlexProgrammerDE**
Hi! Adding this workflow would help new contributors and testers to easily get the newest build without downloading and building salhack themselfes.

### CODE REVIEW

**Comment by ionar2** [comment]
Thank you for your PR :)

**Comment by ionar2** [comment]
So I think we need to run setupDecompWorkspace with this so the build doesn't fail?

**Comment by AlexProgrammerDE** [comment]
@ionar2 i will test it in my fork.

**Comment by dominikaaaa** [comment]
Yes you do need that. Actions also has a cache plugin so you only need to run that once.

**Comment by ionar2** [comment]
Cool, sounds good, create another PR when ready. 👍

**Pull request merged**
