### PR TITLE
Fix actions build

### PR DESCRIPTION
**Pull request by AlexProgrammerDE**
Still draft dont merge.

### CODE REVIEW

**Comment by AlexProgrammerDE** [comment]
@dominikaaaa do we need the whole build folder too or is just the rease enough?

**Comment by dominikaaaa** [comment]
Just the release would be good

**Comment by AlexProgrammerDE** [comment]
Can be merged now.

**Comment by dominikaaaa** [comment]
maim-2020-05-28-11-17-25
epic

**Comment by AlexProgrammerDE** [comment]
Btw does adding github need some docs?

**Comment by dominikaaaa** [comment]
For what?

**Comment by AlexProgrammerDE** [comment]
It took quite some time for me to understand how salhack works. I thought first it gets installed like Impact. 😄

**Comment by dominikaaaa** [comment]
Ehh maybe having installing instructions in the readme would be nice

**Comment by AlexProgrammerDE** [comment]
Yes that was my idea.

**Comment by dominikaaaa** [comment]
Go for it :+1:

**Comment by ionar2** [comment]
Yeah that sounds good.

Also please squash before merging next time @dominikaaaa

**Comment by dominikaaaa** [comment]
Oh sorry, forgot about that. It defaults to squash in my repo

**Pull request merged**
